name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      
      - name: Show Zig version
        run: zig version
      
      - name: Build
        run: zig build
      
      - name: Run tests
        run: zig build test
      
      - name: Format check
        run: zig fmt --check .